### ISSUE TITLE
Define list of file extensions to display plugin context menu item

### ISSUE THREAD

**Issue by AKryukov92** [ivanovych666/intellij-json-sorter-plugin#3]
Currently "JSON Sorter" context menu item appears only in files with extension ".json".
Sometimes JSONS are stored in files with other extension.
It would be great if there were a way to define custom list of file extensions.

**Comment by tozarko-softjourn** [comment]
What is the reason to store JSON with a different extension than ".json"? Also, how IDE works with such "JSON" files?

**Comment by ivanovych666** [comment]
What is the reason to store JSON with a different extension than ".json"? Also, how IDE works with such "JSON" files?

**Comment by AKryukov92** [comment]
IDE (2019.1) treats them as plain text.

Actual reasoning behind storing json with different extension in my example is unknown for me.
It is behaviour of third-party software named Pentaho CDE, which is used in our project.

We are storing reporting files in git. Pentaho shuffles content of json files. By sorting keys in JSON we want to achieve meaningful diffs.

**Comment by ivanovych666** [comment]
Ok, I understand the reason, but if IDE won't work with these files as with JSON then I'm not sure if this plugin can work with this correctly because it uses IDE formatting functionality which can throw an error.
1. I should test if we can work with different extensions.
2. I don't know how to add support for different extensions. I have a lack of experience with Java and even less with IDE plugins. So I can't guarantee anything. If you have some ideas then please create a pull request.

**Comment by AKryukov92** [comment]
Thank you for your response anyway.

**Comment by ivanovych666** [comment]
Hi, I found how you can solve your problem. You just need to associate your files with JSON in your IDE settings. If you do this, then all JSON features will be available for you in the editor including JSON Sorter plugin actions. Please let me know if this works for you.

Displaying this plugin's actions for any file type is not a good idea. Right now, this plugin checks if a file is associated with JSON or if it has .json extension and I think this is correct behavior.

**Comment by AKryukov92** [comment]
Great. Than you for your time.
